### ISSUE TITLE
"Payment source required to redeem gift"

### ISSUE THREAD

**Issue by Dyno2550** [Giggl3z/Discord-Nitro-Redeemer#6]
![image](https://user-images.githubusercontent.com/59626281/71931501-de5b2b80-316b-11ea-9861-1e8f72261722.png)
 
What means it? 
What do I need to do so this does not happen?

**Comment by Parritz** [comment]
i have the same issue

**Comment by Dyno2550** [comment]
All I know is that this happens with Nitro's gifts 3 months

**Comment by Giggl3z** [comment]
those are xbox gifts, you can ignore them since i cant do much about it
